- Extension/scripts/main.js
Attaches to the use convertible ajax point and submits the result to `/convertible_intake.php`
The submitted data looks like:
```json
{
"convertible": {
"id": 2480,
"name": "Rare Moussu Picchu Treasure Chest",
"type": "rare_moussu_picchu_treasure_chest_convertible",
"quantity": 2,
"class": "convertible"
},
"items": [{
"id": 431,
"name": "Gold",
"type": "gold_stat_item",
"quantity": 400000,
"class": "stat"
}, {
"id": 644,
"name": "Points",
"type": "point_stat_item",
"quantity": 400000,
"class": "stat"
}, {
"id": 928,
"name": "Ancient Charm",
"type": "ancient_trinket",
"quantity": 80,
"class": "trinket"
}],
"extension_version": 11220
}
```
Ref: #32
> Submit convertible output

- Server/scripts/converter.js
- Server/scripts/loot.js
- Server/searchByItem.php
increased displayed sigfigs for the "average items" column from 3 to 5, for more precision on rare items like UC.
> item rate sigfigs increased from 3 to 5

- DB/mh_db_auto_backup.sh
- DB/mh_db_auto_backup_nightly.sh
Modified the DB backup scripts to cURL out to a Docker Hub endpoint that will trigger my image builds.
> Added remote triggers for Docker image builds

- Server/loot.php
- Server/scripts/loot.js
- Server/searchByItem.php
DO NOT MERGE until we can deploy the following:
```
-- Prepare drops table
alter table mhhunthelper.drops add column drop_count int, add column min_amt int, add column max_amt int;
DROP PROCEDURE IF EXISTS mhhunthelper.update_drops;
DELIMITER $$
$$
CREATE DEFINER=`root`@`127.0.0.1` PROCEDURE `mhhunthelper`.`update_drops`(
IN `table_name` VARCHAR(255),
IN `from_time` VARCHAR(255),
IN `until_time` VARCHAR(255)
)
BEGIN
CALL exec_query(CONCAT('DROP TABLE IF EXISTS mhhunthelper.drops', table_name, '_temp;'));
CALL exec_query(CONCAT('CREATE TABLE mhhunthelper.drops', table_name, '_temp LIKE mhhunthelper.drops;'));
CALL exec_query(CONCAT('ALTER TABLE mhhunthelper.drops', table_name, '_temp AUTO_INCREMENT=1;'));
CALL exec_query(CONCAT('INSERT INTO mhhunthelper.drops', table_name, '_temp …
```
> Drop chance added to external pages

- CONTRIBUTING.md
Originally just meant to change `Server/` to `src/`, but there were other inaccuracies.
> CONTRIBUTING.md revamp + improvements

- src/countdown.php
- src/scripts/countdown.js
Need to add a link to this somewhere. And this is just a first draft, we can customize this much more.
> Added initial countdown with a title

- src/faq.php
- src/index.php
not sure what else to add. Feel free to proof read, edit, remove my rants, add more useful stuff.
> faq page and link

- src/searchByItem.php
Part of #149  This update has searchByItem.php use the new aggregate table and return more fields. Tested locally.
> Updated to add new columns, use new aggregate table

- .gitignore
- docker-compose.yml.example
- src/scripts/converter.js
can't test on local yet, since we only back it up once a week
> Converter fix nulls

- src/reverse-mapper.php
- src/scripts/reverse-mapper.js
- src/searchByItem.php
literally copied and changed few things in mapper.php and mapper.js, then added one query paragraph to searchByItem.php
> Adding-reverse-mouse-mapper

- src/scripts/attraction.js
- src/scripts/converter.js
- src/scripts/loot.js
- src/scripts/mapper.js
- src/scripts/reverse-mapper.js
> fixing-special-characters-encoding-display

- CONTRIBUTING.md
- src/config.php.example
Modifies config example & contributing doc to make it easier to get started, just rename file or copy-paste.
> Fix syntax in default config + contributing doc

- src/check-userid.php
- src/db-connect.php
- src/map_intake.php
- src/userid-from-hash.php
- Added other dbs to db-connect.php as on-demand (by calling their function)
- Renamed $pdo to $pdo_map to differentiate in map_intake.php
- Added check_userid.php to convert hunter id hash to user_id
- Added user_id to map_records (to be able to show user map history later too)
> Switching to client side user id hash

- src/hunt-intake.php
For Issue #217 
Note that it requires deploying a table into the hunthelper database.
> added hunt_pillage logic

- src/hunt-intake.php
Moved Lucky catch info to the hunts table where it belongs.
In the future if the lucky catch flag is promoted in the hunt object it can be processed in the same section or in the $bindings part.
> Is lucky catch

- src/hunt-intake.php
- src/locations/claw_shot_city.php
- src/locations/locations.php
More hunt_details can be moved to their own table by location. This is the start with Claw Shot City, a very simple one, being implemented. 
DDL will be in a related issue.
> Start Processing More Hunt Details

- src/rejection_intake.php
- refactored field checking to error out on specific field
- added extension_version to field checking and recording
- removed function that is only used once with array that it returns
- simplified array_slice logic
- sort array by keys (timestamp) descending before and after editing it
- removed explicit passing of POST super globals
> refactoring rejection

- src/rejections.php
- src/scripts/attraction.js
- src/scripts/converter.js
- src/scripts/loot.js
- src/scripts/mapper.js
- src/scripts/reverse-converter.js
- src/scripts/reverse-mapper.js
- src/searchByItem.php
- as discussed removing outdated manipulation of db items
- fixing rejections.php to show latest version
Tested on local docker
> Fixing special characters and rejections

- insert_gold_values.php
Slight refactoring of cron script that updates gold values to make it easier to update custom gold values for untradeable items. Added custom gold value definitions for Gold (item id 431) and Magic Essence (item id 211).
> Refactor updating of gold values

- DB/README.MD
- src/uuid.php
* New URL for backups
* Change uuid.php comments about dev env
> Update docs about backup and uuid

- DB/mh_db_auto_backup.sh
- DB/mh_db_auto_backup_nightly.sh
- removing keybase as we don't use it anymore
- also commented out docker build since it doesn't work (requires docker hub pro plan)
> Removing keybase

- src/scripts/reverse-converter.js
- src/styles/main.css
- fixed annoying spacing on front page
- added Opened Total and Opened Single on reverse converter
Tested on local docker.
> Fixing display issues

- src/check-cors.php
- src/uuid.php
This should only affect the dev mode for UUID.php as seen by removing the commented lines and moving the cors check above it.
> Allow OPTIONS preflight request
